### ISSUE TITLE
KeyError: 'Non-existent config key: TEST.DSR'

### ISSUE THREAD

**Issue by woshizhangcheng** [JDAI-CV/Partial-Person-ReID#13]
使用默认配置 ./Partial-Person-ReID/projects/PartialReID/configs/partial_market.yml 文件，指标如下
![PartialiLIDS](https://user-images.githubusercontent.com/34908468/87620494-4c9f2d00-c751-11ea-8d94-051c1a4a888b.jpg)
![OccludedREID](https://user-images.githubusercontent.com/34908468/87620504-51fc7780-c751-11ea-8a75-535feaed37d4.jpg)
![PartialREID](https://user-images.githubusercontent.com/34908468/87620505-532da480-c751-11ea-9dd1-5c1e8d287bca.jpg)

可视化运行:
```
python visualize_result.py --config-file '../logs/partial/config.yaml' \
--parallel --vis-label --dataset-name 'Market1501' --output '../logs/partial_vis' \
--opts MODEL.WEIGHTS "../logs/partial/model_final.pth"
```
提示：
```
Traceback (most recent call last):
  File "visualize_result.py", line 105, in <module>
    cfg = setup_cfg(args)
  File "visualize_result.py", line 32, in setup_cfg
    cfg.merge_from_file(args.config_file)
  File "../fastreid/config/config.py", line 110, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "../fastreid/config/config.py", line 121, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/opt/conda/lib/python3.7/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/opt/conda/lib/python3.7/site-packages/yacs/config.py", line 464, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/opt/conda/lib/python3.7/site-packages/yacs/config.py", line 477, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: TEST.DSR'
```
config.yaml
```
CUDNN_BENCHMARK: true
DATALOADER:
  NUM_INSTANCE: 4
  NUM_WORKERS: 0
  PK_SAMPLER: true
DATASETS:
  COMBINEALL: false
  NAMES:
  - Market1501
  TESTS:
  - PartialREID
  - PartialiLIDS
  - OccludedREID
INPUT:
  DO_AUGMIX: false
  DO_AUTOAUG: false
  DO_CJ: false
  DO_FLIP: true
  DO_PAD: false
  FLIP_PROB: 0.5
  PADDING: 10
  PADDING_MODE: constant
  REA:
    ENABLED: false
    MEAN:
    - 123.675
    - 116.28
    - 103.53
    PROB: 0.5
  RPT:
    ENABLED: false
    PROB: 0.5
  SIZE_TEST:
  - 384
  - 128
  SIZE_TRAIN:
  - 384
  - 128
MODEL:
  BACKBONE:
    DEPTH: 50
    LAST_STRIDE: 1
    NAME: build_resnet_backbone
    NORM: BN
    NORM_SPLIT: 1
    PRETRAIN: true
    PRETRAIN_PATH: ./checkpoints/resnet50_ibn_a.pth.tar
    WITH_IBN: true
    WITH_NL: false
    WITH_SE: false
  HEADS:
    CLS_LAYER: linear
    IN_FEAT: 2048
    MARGIN: 0.15
    NAME: DSRHead
    NECK_FEAT: before
    NORM: BN
    NORM_SPLIT: 1
    NUM_CLASSES: 751
    POOL_LAYER: avgpool
    REDUCTION_DIM: 512
    SCALE: 128
  LOSSES:
    CE:
      ALPHA: 0.3
      EPSILON: 0.1
      SCALE: 1.0
    FL:
      ALPHA: 0.25
      GAMMA: 2
      SCALE: 1.0
    NAME:
    - CrossEntropyLoss
    - TripletLoss
    TRI:
      HARD_MINING: false
      MARGIN: 0.3
      NORM_FEAT: false
      SCALE: 1.0
      USE_COSINE_DIST: false
  META_ARCHITECTURE: PartialBaseline
  OPEN_LAYERS:
  - ''
  PIXEL_MEAN:
  - 123.675
  - 116.28
  - 103.53
  PIXEL_STD:
  - 58.395
  - 57.120000000000005
  - 57.375
  WEIGHTS: ../logs/partial/model_final.pth
OUTPUT_DIR: logs/partial
SOLVER:
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 2.0
  CHECKPOINT_PERIOD: 2000
  DELAY_ITERS: 100
  ETA_MIN_LR: 3.0e-07
  FREEZE_ITERS: 0
  GAMMA: 0.1
  HEADS_LR_FACTOR: 1.0
  IMS_PER_BATCH: 64
  LOG_PERIOD: 200
  MAX_ITER: 6000
  MOMENTUM: 0.9
  OPT: Adam
  SCHED: WarmupMultiStepLR
  STEPS:
  - 3000
  - 5000
  SWA:
    ENABLED: false
    ETA_MIN_LR: 3.5e-06
    ITER: 0
    LR_FACTOR: 10.0
    LR_SCHED: false
    PERIOD: 10
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 600
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0
TEST:
  AQE:
    ALPHA: 3.0
    ENABLED: false
    QE_K: 5
    QE_TIME: 1
  DSR:
    ENABLED: true
    LAMB: 0.5
  EVAL_PERIOD: 1000
  IMS_PER_BATCH: 512
  METRIC: cosine
  PRECISE_BN:
    DATASET: PartialREID
    ENABLED: false
    NUM_ITER: 300
  RERANK:
    ENABLED: false
    K1: 20
    K2: 6
    LAMBDA: 0.3
```
